### ISSUE TITLE
Error when running PG suite in Ecto

### ISSUE THREAD

**Issue by josevalim** [elixir-ecto/db_connection#168]
```
21:37:16.684 [error] GenServer #PID<0.1349.0> terminating
** (ArgumentError) argument error
    (stdlib) :ets.give_away(#Reference<0.3176524715.3721527297.114896>, #PID<0.1346.0>, {:checkin, #Reference<0.3176524715.3721527300.106357>, -576460736782})
    (db_connection) lib/db_connection/holder.ex:32: DBConnection.Holder.update/4
    (db_connection) lib/db_connection/connection.ex:336: DBConnection.Connection.pool_update/2
    (connection) lib/connection.ex:810: Connection.handle_async/3
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:connected, #Reference<0.3176524715.3721396225.114895>}}

21:37:16.684 [error] GenServer #PID<0.1350.0> terminating
** (ArgumentError) argument error
    (stdlib) :ets.give_away(#Reference<0.3176524715.3721527298.114281>, #PID<0.1346.0>, {:checkin, #Reference<0.3176524715.3721527300.106357>, -576460736782})
    (db_connection) lib/db_connection/holder.ex:32: DBConnection.Holder.update/4
    (db_connection) lib/db_connection/connection.ex:336: DBConnection.Connection.pool_update/2
    (connection) lib/connection.ex:810: Connection.handle_async/3
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:connected, #Reference<0.3176524715.3721396226.114280>}}

21:37:16.685 [error] GenServer #PID<0.1348.0> terminating
** (ArgumentError) argument error
    (stdlib) :ets.give_away(#Reference<0.3176524715.3721527298.114285>, #PID<0.1346.0>, {:checkin, #Reference<0.3176524715.3721527300.106357>, -576460736782})
    (db_connection) lib/db_connection/holder.ex:32: DBConnection.Holder.update/4
    (db_connection) lib/db_connection/connection.ex:336: DBConnection.Connection.pool_update/2
    (connection) lib/connection.ex:810: Connection.handle_async/3
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:connected, #Reference<0.3176524715.3721396226.114284>}}
```

**Comment by josevalim** [comment]
If `pool_update` fails, we need to shutdown the connection.
